### PR TITLE
Updating OS versions for Xcode 11.2.1

### PR DESCRIPTION
**Pull request by noobs2ninjas**

### CODE REVIEW

**Review by drdaz — APPROVED** [review]
Looks fine to me.

**Comment by drdaz** [comment]
@noobs2ninjas I can't merge this, can you?

**Comment by noobs2ninjas** [comment]
@drdaz I guess only @TomWFox. Guess its not added to the iOS team yet.

**Comment by TomWFox** [comment]
It's on the iOS team and set to write so I have no idea why you wouldn't be able to merge 😅

**Pull request merged**
