### PR TITLE
Update to build to use current Apple OS'

### PR DESCRIPTION
**Pull request by drdaz**

### CODE REVIEW

**Comment by TomWFox** [comment]
@drdaz I've got write access for this repo now, could you briefly explain what xctoolchain does / how it fits in with the iOS sdk? (I have no idea!)

**Comment by drdaz** [comment]
@TomWFox Actually the very short description in the repo describes it quite well; scripts and configs used to build (and perhaps test?) using Xcode.

**Comment by drdaz** [comment]
When you (or the build server) run(s) `bundle exec rake package:release`, these are the scripts and configs that make that happen.

EDIT: Along with the Rakefile in the iOS SDK.

**Comment by drdaz** [comment]
Tbh I'm not sure why all those commits are in this PR. The only change I made yesterday was an update of the OS versions to build against (the last commit; actually the last 2, but they're the same?).

I thought those older commits had long since been merged... not least since I forked from mainline yesterday 🤷🏽‍♂️

**Comment by TomWFox** [comment]
Ok, thanks for explaining that, I'd say this can be merged

**Review by TomWFox — APPROVED** [review]

**Pull request merged**
