### PR TITLE
Updating to OS 13.2.2 because travis documentation is terrible. 

### PR DESCRIPTION
**Pull request by noobs2ninjas**

### CODE REVIEW

**Comment by noobs2ninjas** [comment]
Sorry for doing this again @TomWFox. Travis documentation apparently isnt at all accurate.

**Comment by noobs2ninjas** [comment]
I found out what the deal is for me to push it. On protected branches you have to have two reviewers sign off.

**Review by drdaz — APPROVED** [review]
Again, looks fine to me.

**Review by TomWFox — APPROVED** [review]
Looks fine. I'll remove the protection as two reviewers seems a bit ott for this

**Comment by TomWFox** [comment]
Actually wasn't the number of reviewers there were some other rules about who could push to particular branches but I've removed it now.

**Pull request merged**
