### PR TITLE
Add run failed tests multiple times

### PR DESCRIPTION
**Pull request by cbaker6**
Run failed tests multiple times to gather more information about reasons for failure

### CODE REVIEW

**Comment by cbaker6** [comment]
@drdaz This may help find out what's going on with the failing test. I don't know much about how this toolchain works, so you will want to verify I added the line to the correct place.

You can see how the Swift SDK uses this here: https://github.com/parse-community/Parse-Swift/blob/fe67c8816188df195699a67e61fa19417f94c465/.github/workflows/ci.yml#L21

More info here: https://www.avanderlee.com/debugging/flaky-tests-test-repetitions/?utm_content=buffer05ce6&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by cbaker6** [comment]
Also added some commits from the repo this was forked from as they seem they might be useful

**Review by drdaz — APPROVED** [review]
LGTM. I'll update the pointer in the main SDK repo.

**Comment by drdaz** [comment]
Thanks for this btw; I think it'll be super helpful. I recalled there was something new in XC13 that should help with exactly this issue last time I was working with the SDK, but couldn't for the life of me remember what...

**Comment by drdaz** [comment]
I was a little hasty on the approve; something's off. The options aren't quite coming out in the right place. I'll poke at it.

**Pull request merged**
