### PR TITLE
Updating build_framework to reflect Travis CI changes.

### PR DESCRIPTION
**Pull request by noobs2ninjas**
Apparently Travis changed available simulators to only recent models to run recent versions of OS. Updating everything so that these simulators will be valid for quite sometime.

### CODE REVIEW

**Review by drdaz — APPROVED** [review]
Looks just fine. Hopefully CI likes it 🤞🏼

**Comment by noobs2ninjas** [comment]
I hope so too. I dont even have permission to merge now that you've approved. Think you could do that for me? @drdaz

**Comment by drdaz** [comment]
> I hope so too. I dont even have permission to merge now that you've approved. Think you could do that for me?

'fraid not. I also don't have those powers 😉. @TomWFox can you do your thing here?

**Review by TomWFox — APPROVED** [review]
I’ll get this repo added to the iOS team so you guys have access

**Pull request merged**
